# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\nagentchain\"\xc6\x01\n\tAgentTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.agentchain.TaskType\x12\x11\n\tcode_path\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\x12\x31\n\x06params\x18\x05 \x03(\x0b\x32!.agentchain.AgentTask.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x0b\x41gentResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x1b\n\x0cStateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\rStateResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t*;\n\x08TaskType\x12\x0b\n\x07\x41NALYZE\x10\x00\x12\x0c\n\x08OPTIMIZE\x10\x01\x12\x08\n\x04TEST\x10\x02\x12\n\n\x06REVIEW\x10\x03\x32\x90\x02\n\x0c\x41gentService\x12=\n\x0bProcessTask\x12\x15.agentchain.AgentTask\x1a\x17.agentchain.AgentResult\x12?\n\x08GetState\x12\x18.agentchain.StateRequest\x1a\x19.agentchain.StateResponse\x12>\n\x08SetState\x12\x19.agentchain.StateResponse\x1a\x17.agentchain.AgentResult\x12@\n\x0bHealthCheck\x12\x18.agentchain.StateRequest\x1a\x17.agentchain.AgentResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTTASK_PARAMSENTRY']._loaded_options = None
  _globals['_AGENTTASK_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TASKTYPE']._serialized_start=382
  _globals['_TASKTYPE']._serialized_end=441
  _globals['_AGENTTASK']._serialized_start=28
  _globals['_AGENTTASK']._serialized_end=226
  _globals['_AGENTTASK_PARAMSENTRY']._serialized_start=181
  _globals['_AGENTTASK_PARAMSENTRY']._serialized_end=226
  _globals['_AGENTRESULT']._serialized_start=228
  _globals['_AGENTRESULT']._serialized_end=306
  _globals['_STATEREQUEST']._serialized_start=308
  _globals['_STATEREQUEST']._serialized_end=335
  _globals['_STATERESPONSE']._serialized_start=337
  _globals['_STATERESPONSE']._serialized_end=380
  _globals['_AGENTSERVICE']._serialized_start=444
  _globals['_AGENTSERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
